### ISSUE TITLE
예외 처리

### ISSUE THREAD

**Issue by hyunsuk** [rikapo/tra-la#2]
Mypage 의 [여기](https://github.com/rikapo/tra-la/commit/4544a7630c9e7b9d2550472da91814277a9202bc#diff-bdac5dbf59aaf90352cf369a44fb5ac3R17)에서 $username 이 공백이거나(라우터에서 처리?)
먄약 없는 사용자일 경우의 예외 처리는?

**Comment by rikapo** [comment]
오늘 error.blade.php 뷰 추가하면서 $username 값이 유효하지 않으면 에러 페이지로 가도록 고쳤습니다!
